### PR TITLE
s/insert_annotaions_from_mask/insert_annotations_from_mask

### PR DESCRIPTION
**Pull request by corey-chivers-proscia**
Fix typo in spelling of `annotations`

### CODE REVIEW

**Review by vaughnproscia — CHANGES_REQUESTED** [review]
Name change looks good. Is the new notebook meant to be included in this PR? If so I'll review it 👍

**Comment by corey-chivers-proscia** [comment]
> Is the new notebook meant to be included in this PR?

Yep, @vaughnproscia it calls that method so it's been updated too.

**Comment by vaughnproscia** [comment]
> > Is the new notebook meant to be included in this PR?
> 
> Yep, @vaughnproscia it calls that method so it's been updated too.

Got it 👍 I was expecting like a one line change but git measures the entire file to be changed ha so I wasn't sure. One sec and I'll finish reviewing.

**Review by vaughnproscia — APPROVED** [review]
LGTG!

**Pull request merged**
